x-redash-service: &redash-service
  image: redash/redash:latest
  env_file: .env
  restart: always
  networks:
    - tradeflow_net

services:
  redash-init:
    <<: *redash-service
    command: create_db
    restart: "no"
    depends_on:
      redis:
        condition: service_started

  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    depends_on:
      redash-init:
        condition: service_completed_successfully
      redis:
        condition: service_started

  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      redash-init:
        condition: service_completed_successfully

  worker:
    <<: *redash-service
    command: worker
    depends_on:
      redash-init:
        condition: service_completed_successfully

  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - tradeflow_net

  postgres:
    image: postgres:18
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_init/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    networks:
      - tradeflow_net

  generator:
    build: ./generator
    env_file: .env
    networks:
      - tradeflow_net
    restart: always

networks:
  tradeflow_net:
    driver: bridge

volumes:
  pg_data:
